### Register User
POST https://aksesoris-api-17-296685597625.us-central1.run.app/register
Content-Type: application/json

{
  "name": "tes",
  "email": "tes@gmail.com",
  "password": "123"
}

### Login User
POST https://aksesoris-api-17-296685597625.us-central1.run.app/login
Content-Type: application/json

{
  "email": "tes@gmail.com",
  "password": "123"
}

### Get All Products
GET https://aksesoris-api-17-296685597625.us-central1.run.app/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDg0MzgwMzAsImV4cCI6MTc0ODUyNDQzMH0.ccBL5IBXc4FtTQMq3DxQ9oP5lxKaoGAFeKdOvM5SXck


### Create Product (Login Dulu, Ambil token dari hasil login)
POST https://aksesoris-api-17-296685597625.us-central1.run.app/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDg0NDk5ODksImV4cCI6MTc0ODUzNjM4OX0.2EwEDJcgIV2SgKEbybJXrdxfYgh-V83m-f5CF_PB7fw
Content-Type: application/json

{
  "name": "Gelang Unik Antik Kaciw Kalcer",
  "description": "Anti karat, silver, 100cm",
  "price": 120000,
  "image": "https://i.imgur.com/abcd123.jpg"
}


# Gunakan file upload di REST Client (VSCode extension), atau gunakan Postman untuk unggah gambar
# Contoh isian manual jika tidak pakai file upload:
# name=Gelang Keren&description=Gelang dari kulit asli&price=15000

### Update Product
PUT http://localhost:5000/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDg0MzgwMzAsImV4cCI6MTc0ODUyNDQzMH0.ccBL5IBXc4FtTQMq3DxQ9oP5lxKaoGAFeKdOvM5SXck
Content-Type: application/json

{
  "name": "Gelang Updated",
  "description": "Deskripsi update",
  "price": 18000
}

### Delete Product
DELETE http://localhost:3000/products/1
Authorization: Bearer 

### Get All Transactions
GET http://localhost:3000/transactions
Authorization: Bearer 

### Create Transaction
POST http://localhost:3000/transactions
Authorization: Bearer 
Content-Type: application/json

{
  "productId": 2,
  "quantity": 3,
  "total": 45000
}

### Update Transaction
PUT http://localhost:3000/transactions/1
Authorization: Bearer 
Content-Type: application/json

{
  "quantity": 4,
  "total": 60000,
  "status": "selesai"
}

### Delete Transaction
DELETE http://localhost:3000/transactions/1
Authorization: Bearer
