### Register User
POST https://aksesoris-api-17-296685597625.us-central1.run.app/register
Content-Type: application/json

{
  "name": "tes",
  "email": "tes@gmail.com",
  "password": "123"
}

### Login User
POST https://aksesoris-api-17-296685597625.us-central1.run.app/login
Content-Type: application/json

{
  "email": "ding123@gmail.com",
  "password": "123"
}

### Get All Products
GET https://aksesoris-api-17-296685597625.us-central1.run.app/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDg0MzgwMzAsImV4cCI6MTc0ODUyNDQzMH0.ccBL5IBXc4FtTQMq3DxQ9oP5lxKaoGAFeKdOvM5SXck


### Create Product (Login Dulu, Ambil token dari hasil login)
POST https://aksesoris-api-17-296685597625.us-central1.run.app/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDg3MjI0NTcsImV4cCI6MTc0ODgwODg1N30.TVwFzkgs86CRVUscHNqXTpgs3dm-erPJQDfFS524Q4M
Content-Type: application/json

{
  "name": "Yankees Baseball Cap",
  "description": "Black Color with NY Logo",
  "price": 899090,
  "image": "https://assets.preloved.co.id/products/324414/acf4083a-8273-4c77-94a9-c62077d68157.jpg"
}


# Gunakan file upload di REST Client (VSCode extension), atau gunakan Postman untuk unggah gambar
# Contoh isian manual jika tidak pakai file upload:
# name=Gelang Keren&description=Gelang dari kulit asli&price=15000

### Update Product
PUT http://localhost:5000/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDg0MzgwMzAsImV4cCI6MTc0ODUyNDQzMH0.ccBL5IBXc4FtTQMq3DxQ9oP5lxKaoGAFeKdOvM5SXck
Content-Type: application/json

{
  "name": "Gelang Updated",
  "description": "Deskripsi update",
  "price": 18000
}

### Delete Product
DELETE https://aksesoris-api-17-296685597625.us-central1.run.app/products/1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NCwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDg0NTA0MTIsImV4cCI6MTc0ODUzNjgxMn0.nWhhKYO5ShjQ826ndbHVjYhtNbYgH0z7f8eykJ9qOZA

### Test: Get All Products (Untuk mendapatkan productId)
GET https://aksesoris-api-17-296685597625.us-central1.run.app/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDg3MjU4NjksImV4cCI6MTc0ODgxMjI2OX0.81Cel-LkMVwsPbFDVIgyu1e7jSYFdT1xdgV87z68k-Q
Content-Type: application/json

### Test: Create an Order
POST https://aksesoris-api-17-296685597625.us-central1.run.app/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDg3MjU4NjksImV4cCI6MTc0ODgxMjI2OX0.81Cel-LkMVwsPbFDVIgyu1e7jSYFdT1xdgV87z68k-Q
Content-Type: application/json

{
    "recipientName": "Penerima Contoh",
    "deliveryAddress": "Jalan Contoh No. 123, Kota Contoh, Provinsi Contoh",
    "currency": "IDR",
    "totalAmount": 250000.00,
    "products": [
        {
            "id": 4,
            "name": "Gelang Unik Antik Kaciw Kalcer",
            "pricePerUnit": 120000,
            "imageUrl": "https://static.pullandbear.net/assets/public/67bc/f3e7/a3a94122b112/fcf18e1ea8f3/03997502808-A1M/03997502808-A1M.jpg?ts=1730816156090&w=1082&f=auto",
            "quantity": 1
        },
        {
            "id": 8,
            "name": "Dior Men Necklace",
            "pricePerUnit": 12300000,
            "imageUrl": "https://assets.christiandior.com/is/image/diorprod/LOOK_H_24_3_LOOK_079_E40?$lookDefault_GH-GHC$&crop=568,0,1864,2000&bfc=on&qlt=85",
            "quantity": 2
        }
    ]
}

### Test: Get All Orders for Current User
GET https://aksesoris-api-17-296685597625.us-central1.run.app/orders
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwicm9sZSI6InVzZXIiLCJpYXQiOjE3NDg3MjU4NjksImV4cCI6MTc0ODgxMjI2OX0.81Cel-LkMVwsPbFDVIgyu1e7jSYFdT1xdgV87z68k-Q
Content-Type: application/json